### ISSUE TITLE
Problem with considering a 404 from the ID Store to mean we should deactivate a user

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-sync#1]
As I was diagramming the decision tree based on discussing this sync logic with @wcjr and @lvail, I noticed that it poses a significant risk to considering a `404` response (from the ID Store) to mean that we should deactivate a user.

If either the ID Sync is configured with the wrong URL for the ID Store, or if the URL to the ID Store API changes (which has happened with APIs in the system we're currently using for this), then every user in the organization could be deactivated in a single batch job.

While we could (and perhaps will) put some safeguards in place to prevent deactivating a disproportionately large number of users at once, that is still merely trying to contain a problem that we might be able to simply design out of existence for this system.

What if we refactored the ID Store API to return something else when a user should be deactivated? One possibility would be a `204` (a successful call that indicates there is nothing to return).

@fillup, do you have any thoughts on this?

**Comment by fillup** [comment]
We'll see what we can actually get back from the personnel store.

**Comment by Schparky** [comment]
@forevermatt unless you see this differently, I believe this was adequately addressed by the sync cutoff feature.

**Comment by forevermatt** [comment]
@Schparky, that's fine with me. Thanks.
