### ISSUE TITLE
Revise tests to communicate with a real (local) instance of ID Broker

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-sync#10]
The current tests (as of #9) just use a fake ID Broker, but whenever the ID Broker is ready, we could change the `docker-compose.yml` file for the ID Sync to use a real ID Broker instance for it's tests, giving us a greater level of confidence that the actual integration is working.

**Comment by forevermatt** [comment]
We now have tests that check the basic ability of ID Sync to interact with ID Broker. I didn't have the sync tests use the ID Broker because the ID Broker API doesn't easily allow removing records (by design), which makes it hard to set up the state for a test to run.

**Comment by devon-sil** [comment]
This appears to have been completed.
