### ISSUE TITLE
Auto-activating a user?

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-sync#3]
When the ID Sync receives user info from the ID Store, that therefore means that the user is active in the ID Store. That presumably means that for every POST we make to `/user` to create/update a user record, the ID Sync will need to add a `"active": "yes"` line to it. Does that seem right? Would it be better to have the ID Broker automatically set "active" to "yes" for every `POST /user` it receives where "active" is not specified?

**Comment by fillup** [comment]
I'm fine either way. id-sync will be including a `"locked": "yes/no"` in each post/put for a user based on the value that it gets from personnel.

**Comment by forevermatt** [comment]
Took the approach of having the ID Sync specifically send `'active': 'yes'` to the ID Store when updating a user: d77251b
