### ISSUE TITLE
Need to change approach to sync

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-sync#4]
We had been thinking that we could simply get the list of all users from the ID Store, then `POST` each to the ID Broker. However, that won't tell us about users in the ID Broker that need to be removed, and that requires that a single endpoint (we were using `POST /user`) accept both creates and updates.

Since we keep hitting complications caused by allowing `POST /user` to also accept updates, and because we need the list of users in the ID Broker in order to know if any need to be removed, it looks like we'll want to revise this general approach.

The current (tentative) plan is to get the list of users from the ID Store, get the list of users from the ID Broker (including at least `employee_id`, but possibly also `active`), then go through the two lists making either `POST /user` (with all required fields), `PUT /user/{employee_id}` (with all available fields), or `PUT /user/{employee_id}` (with `{"active":"no"}`) for each record, as applicable.

@wcjr and @lvail, how does that sound to you?

**Comment by forevermatt** [comment]
Here are the scenarios I see:
- If a user is in both the ID Store list and the ID Broker list, send the ID Broker a `PUT /user/{employee_id}` to update it.
- If a user is in the ID Store list but not the ID Broker list, send a `POST /user` with the available fields.
- If a user is _not_ in the ID Store list but is in the ID Broker list, send a `PUT /user/{employee_id}` with `{"active":"no"}` to deactivate it (if it's currently active).

Note that this assumes that the list of users received from the ID Broker includes deactivated users (otherwise the ID Sync would end up trying to do a `POST /user` and getting a conflict because a user record already exists in the ID Broker with that `employee_id`).

**Comment by fillup** [comment]
I'm fine with the proposed change.

**Comment by forevermatt** [comment]
Since this issue is basically specific to the sync-all-users scenario, I think the merging of #9 completed this issue.
