### ISSUE TITLE
Send alert email when sync aborted due to safety cutoff

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-sync#52]

**Comment by Schparky** [comment]
This was implemented on commit https://github.com/silinternational/idp-id-sync/commit/f7b05c53ee76c495ee165a1ab6303cd0755de53e and released at version 1.0.0. 

Confirmed on 2022-01-11. 
![image](https://user-images.githubusercontent.com/3172830/149006037-7fe5bb29-9750-47a3-b32f-d165a81171fa.png)
