### ISSUE TITLE
Hitting rate limit when updating about 100 users in a Google Sheet

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-sync#74]
https://github.com/silinternational/idp-id-sync/blob/664f539ef5f05cfcf15b58f074739422cd282463/application/common/components/adapters/GoogleSheetsIdStore.php#L250

We're sometimes hitting a rate limit on the Google Sheets API:
> Quota exceeded for quota group 'WriteGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number: (our project number)'.

Here is some related information from Google about rate limits / quotas:
https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas

I suspect we'll eventually need to refactor this GoogleSheetsIdStore adapter to update the last-synced column as a single batch operation, rather than a separate write call for each row's last-synced cell. Simply reducing the frequency of our syncs doesn't seem to fix it, since each sync will be trying to perform more than 100 write operations in less than 100 seconds (if there are about a hundred users to sync).

**Comment by forevermatt** [comment]
Another (possibly better) approach would be to wait to update that last_synced cell for each user until that user's data has actually been synchronized with ID Broker, and intelligently handle these rate limit exceptions (Google_Service_Exception with a code of 429).

**Comment by Schparky** [comment]
For the sake of documentation, and so i don't have to later repeat the research I just did, the current implementation is as described in the issue description. That is, all of the last-synced column is updated 100 cells at a time. Thus, the rate limit would theoretically not be hit until the user list exceeds 900 (the read query, plus 9 updates of 100 cells each). That is assuming that those would all be within one second, and no other calls happened in that same 1 second period of time.
